### ISSUE TITLE
Set min max according to the values except nodata

### ISSUE THREAD

**Issue by ruz76** [OpenGeoLabs/qgis-world-from-space-plugin#13]
The raw TIFF is strethed to the data that also include -999 (-998). We should keep just relevant data.

**Comment by kalab-oto** [comment]
-998 are nodata, but -999 is cloud mask. There are to ways how to handle it:

- ignore clouds - count clouds as nodata
- set symbology to palette with extra color (i.e. red) for -999 (clouds)
