### ISSUE TITLE
Shapefile layer is not supported

### ISSUE THREAD

**Issue by Bohovic** [OpenGeoLabs/qgis-world-from-space-plugin#23]
Polygons for processing can be selected only from Temporary Scratch Layer, not for shapefile loaded from disk.

**Comment by kalab-oto** [comment]
This is maybe related (and probably will be resolved) with #16. And maybe its specific for ESRI Shapefile - QGIS for some reason export single shp polygon layer with geometry `Polygon (Polygon)` to `Polygon (MultiPolygon)` with no regards to export option. Temporary Scratch Layer with geometry `Polygon (Polygon)` works fine, same as exported  `GPKG`, which keeps single polygon geometry.

![obrazek](https://user-images.githubusercontent.com/13303725/115522489-6f381680-a28c-11eb-9eb5-7cf7f7989b9d.png)
