### ISSUE TITLE
Polygon issue

### ISSUE THREAD

**Issue by Bohovic** [OpenGeoLabs/qgis-world-from-space-plugin#27]
It responds "The response does not contain valid data to show." even when not reasonable. It seems there is some issue with polygons, even within same layer some works well others not.

**Comment by ruz76** [comment]
Can you send us the layer for testing?

**Comment by Bohovic** [comment]
[vinice.zip](https://github.com/OpenGeoLabs/qgis-world-from-space-plugin/files/6450237/vinice.zip)

**Comment by ruz76** [comment]
Probably fixed with change of the flow. Now it works on this layer.
