### ISSUE TITLE
Plugin name

### ISSUE THREAD

**Issue by Bohovic** [OpenGeoLabs/qgis-world-from-space-plugin#28]
Please rename it to "DynaCrop" instead of WfS.

**Comment by janchytry** [comment]
The names are still inconsistent in my view, at least in the English language version. 

- In the plugin panel it says "Dyna Crop"
- In the QGIS plugin repository name and description also "Dyna Crop"
- The icon alt is "Show DynaCrop widget", in the _Plugins_ menu it is "DynaCrop" - that's correct.

It should be "DynaCrop" at all instances. :)
