### ISSUE TITLE
Inconsistent response for longer time series

### ISSUE THREAD

**Issue by janchytry** [OpenGeoLabs/qgis-world-from-space-plugin#33]
When time series for a longer period is fired, sometimes it fails with response aka "request failed" (however, the request is not terminated). Second time, it usually passes and outputs a chart.
PS: The field I used was small and had a very simple geometry, was in 4326.

**Comment by ruz76** [comment]
Could you send us the geometry and parameters, please.

**Comment by ruz76** [comment]
Could you send us exact message. There are several phases when the request may fail and they should have different messages.

**Comment by janchytry** [comment]
Unfortunately, I did not remember the message precisely and can no longer reproduce the issue (probably cache?). As I said it worked.

Geometry: MultiPolygon (((16.89040687 48.86621973, 16.88992691 48.86567103, 16.88846372 48.86620133, 16.88892038 48.86675002, 16.89040687 48.86621973))) (weird I know, but it worked and the feature is actually single polygon, this is just what QGIS returned)
request: time series
date from: 2020-05-13
date to: 2021-05-13

**Comment by ruz76** [comment]
Probably fixed.
