### ISSUE TITLE
implicit value of parameter "SMI enabled" 

### ISSUE THREAD

**Issue by Bohovic** [OpenGeoLabs/qgis-world-from-space-plugin#35]
Implicit value of parameter "SMI enabled" must be set false, otherwise processing of new polygon takes more than 10minutes. Use of this may be enabled by dedicated checkbox with some info panel (takes around 10 minutes).

If this is already set, there might be different problem, probably to short time of waiting. Most of the requests fails.

**Comment by ruz76** [comment]
Yes. This is bug. I see in the cod that now the smi_enabled is True in any case. This is not correct. It has to be True only if the user selects SMI index.
