### ISSUE TITLE
The orded of dates in graph

### ISSUE THREAD

**Issue by ruz76** [OpenGeoLabs/qgis-world-from-space-plugin#6]
If you use 1.08.2020 to 30.8.2020 for NDVI the graph looks quite strange. It may be wrong order of the values.
![image](https://user-images.githubusercontent.com/15860810/112362081-5a3f8600-8cd4-11eb-9abd-8059755154d0.png)

Or it may be a problem if we draw in the same graph that the other have different list of values. Different area.

**Comment by kalab-oto** [comment]
Can't reproduce. Works fine for me. I tried same date for all polygons.
![obrazek](https://user-images.githubusercontent.com/13303725/114320473-53a77000-9b16-11eb-834a-8eb5e11c2d0a.png)

**Comment by kalab-oto** [comment]
I see that issue today too. It is possible caused by appending list of dates of each polygon if date is not in all registered polygons. Strange that works fine form me yesterday.
